name: Build on PROD

on:
  push:
    branches:
      - production
  repository_dispatch:
    types:
      - build-prod
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-prod:
    uses: Obligatorio-DevOps-175577-181513/Frontend/.github/workflows/deploy-to-s3.yml@production
    with:
      CI_ENV: production
      CONTENTFUL_ENVIRONMENT: 'production'
    secrets:
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_ORIGIN_BUCKET: ${{ secrets.S3_ORIGIN_BUCKET_PRD }}